- opac/webapp/static/sass/jquery.typeahead.scss
- opac/webapp/templates/article/includes/recent_articles_row.html
- opac/webapp/templates/collection/index.html
- opac/webapp/templates/news/includes/collection_news_row.html
- opac/webapp/templates/press_release/includes/press_releases_row.html
Adiciona o comportamento de slick slider nos cards da home, padronizando assim com os demais cards.
Ao receber esse PR, gere os arquivos estáticos css e abra a home do sistema. Os cards devem estar sendo exibidos com o novo formato.
Apenas navegue pela Home.
É possível que existam muitos cards e por isso apareçam muitos dots para navegação entre eles. Estamos trabalhando para prever uma quantidade maior de cards e solucionar possíveis situações como esta.
Não há tickets para este ajuste.
> Ajustes nos cards da Home

- opac/webapp/main/views.py
- opac/webapp/templates/article/base.html
- opac/webapp/templates/article/includes/floating_menu.html
- opac/webapp/templates/base.html
- opac/webapp/templates/issue/includes/alternative_header.html
- opac/webapp/templates/journal/includes/levelMenu.html
Esse PR, adiciona na pagina do artigos: 
* O novo formato de como citar o artigo, igual ao do projeto **opac**
* Adiciona o SCIMAGO institution, igual ao do projeto **opac**
* Adiciona o link correto para a busca na **home do periódico**
* Remove javascript que inutilizados que produz erro.
Por commit.
Rodando a aplicação local e acessando a página do artigo e página do periódico.
Essas são funcionalidades que existem no projeto opac e deve ser incorporadas no opac_5
Existe ajuste de interface que precisam ser feitas, veja: 
N/A
N/A
> Atualiza alguns itens do OPAC

- requirements.txt
Resolve questões da página do artigo
packtools 3.2.4
- Modifica a apresentação de xref[@ref-type="bibr"] (python3) by @robertatakenaka in #520
packtools 3.2.3
- [página do artigo] Corrige apresentação de lista do tipo "simple" by @robertatakenaka in #466
- [opac_5] Resolve apresentação de fn[@fn-type='data-availability'] e da seção que destaca a disponibilidade de dados by @robertatakenaka in #492
- [opac_5] Corrige a ausência do link para o preprint e corrige o rótulo que acompanha o link by @robertatakenaka in #494
- Página do Artigo - Adiciona apresentação de contrib/bio by @robertatakenaka in #507
> Atualiza a versão de packtools 3.2.4 (Resolve questões da página do artigo)

- docker-compose.yml
Adiciona o minio no arquivo de produção do docker-compose.yml.
No arquivo docker-compose.yml
Executando: 
```shell
docker-compose -f docker-compose.yml up -d
```
Essa alteração é necessária para a documentação do ambiente em produção, segue documento: https://docs.google.com/document/d/1CnjcBV2PtjB8T01TL73HvPqmnng6f73tzQNpOHDlTDg/edit
Imagem do minio rodando na porta 9000: 
N/A
N/A
> Adiciona o minio no arquivo de produção do docker-compose.yml.

- docker-compose.yml
- nginx/conf.d/opac.conf
Adiciona o serviço do nginx para o ambiente de produção.
Sugiro que seja executado os seguintes comandos: 
```shell
docker-compose -f docker-compose.yml up -d
```
Deveria de ter o nginx rodando: 
Acessando localmente pelo browser deve aparece a seguinte tela: 
Acessando o browser com o endereço: http://localhost ou http://0.0.0.0
Essa alteração é necessária para a documentação do ambiente em produção, segue documento: https://docs.google.com/document/d/1CnjcBV2PtjB8T01TL73HvPqmnng6f73tzQNpOHDlTDg/edit
N/A
Não existe ticket para essa atividade.
N/A
> Adiciona o serviço do nginx para o ambiente de produção.

- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/templates/journal/includes/levelMenu.html
Corrige a identificação de "último número".
Um "número" (fascículo) é um fascículo da publicação regular ou contínua, não pode ser considerado nem especial, nem suplemento, nem ahead of print. No entanto, para a navegação entre todos os componentes do periódico (números regulares, contínuos, especiais, suplementos, ahead of print), todos são considerados. 
Por commits
Navegando entre as páginas do periódico: home, about, fascículos etc, nas páginas.
Ler #99
n/a
n/a
#99 
n/a
> Corrige a identificação de "último número"

- docker-compose.yml
- opac/webapp/config/default.py
- opac/webapp/main/views.py
- opac/webapp/templates/issue/toc.html
Alteração para (re)apresentar os artigos filtrados por seções.
Em particular, os periódicos multidisciplinares e os de publicação contínua, precisam do filtro de seção para apresentar os artigos. Inicialmente vamos tratar apenas dos periódicos multidisciplinares, devido a questões pendentes sobre correspondências de idiomas das seções.
por commits
Altere o valor de `FILTER_SECTION_ENABLE_FOR_MIN_STUDY_AREAS = int(os.environ.get("OPAC_FILTER_SECTION_ENABLE_FOR_MIN_STUDY_AREAS", 5))` para 1 de modo que todas os sumários terão que apresentar as seções.
Acessando os sumários
Habilitar o sumário depende `OPAC_FILTER_SECTION_ENABLE` estar como `True`.
Para não gerar um link que os usuários possam copiar e para que os buscadores não indexem a página com os artigos filtrados e mostrem menos …
> Alteração para (re)apresentar os artigos filtrados por seções (WIP)

- opac/webapp/controllers.py
- opac/webapp/main/views.py
Melhora Corrige identificação de último número". No PR do issue #99, havia uma nova consulta à base de dados que era desnecessária. Também foi eliminada a chamada a `utils.fix_journal_last_issue()`.
por commits
Ver #99
Esta correção foi aplicada no opac https://github.com/scieloorg/opac/pull/2937
n/a
#99, https://github.com/scieloorg/opac/pull/2937, #108
n/a
> Melhoria em desempenho de "Corrige identificação de último número"

- opac/webapp/templates/base.html
- opac/webapp/templates/collection/includes/journal_list_row.html
- opac/webapp/templates/issue/toc.html
Corrige a chamada do css do design system para evitar a demora no carregamento.
Corrige o link dos periódicos na listagem de periódicos, removendo a vírgula do link.
Corrige a lista de sumário, removendo o header "Artigos" do topo da lista.
Carregue os arquivos e de um refresh no sistema. Perceba que o CSS não deve demorar a ser carregado.
Após, navegue até a lista de periódicos e verifique o link de cada um dos periódicos sem a vírgula incluída no link.
Na tela do sumário, perceba que o título "Artigos" foi removido.
Siga os passos descritos anteriormente.
-
#104 
-
> Correção da chamada do css, Correção do link no título do periódico, remoção do header da tabela do sumário

- requirements.txt
Atualiza dependência opac_schema para versão v2.8.0
pelos commits
1. docker-compose -f docker-compose-dev.yml build --no-cache
2. make up 
n/a
n/a
n/A
n/a
> Atualiza dependência opac_schema para versão v2.8.0

- Makefile
Atualiza  Makefile para otimização de atualização dos containers.
pelo commits
```
make update compose=docker-compose.yml
```
N/A
N/A
#164 
N/A
> Atualização do Makefile para otimização de atualização dos containers.

- opac/webapp/templates/includes/share.html
- opac/webapp/templates/journal/detail.html
Fix: Remoção do atributo autoheight nos slides pois foi feita uma correção no ds que corrige a necessidade deste.
Fix: Inclusão do componente addtoany para elementos share.
Fix: Correção de layout para impedir quebra de layout ao abrir dropdown share na home do periódico no mobile.
Corrige a necessidade da função javascript para redimensionar os cards.
Insere componentes addtoany ao template share, possibilitando uma grande variedade de redes sociais para se compartilhar.
Carregue os arquivos e navegue no sistema. Todos os dropdowns share devem exibir os novos elementos do addtoany. Ver print.
Os cards serão redimensionados automaticamente após a atualização do design system.
Siga os passos descritos anteriormente.
O ajuste referente aos cards depende da atualização do design system. Essa …
> Fix: Cards e Share

- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/utils/utils.py
Habilita acesso à página informativa com base na coleção configurada na interface administrativa
pelos commits
Acessar página informativa
N/A
N/A
#192 
N/A
> Habilita acesso à página informativa com base na coleção configurada na interface administrativa

- opac/webapp/config/default.py
- opac/webapp/templates/base.html
- opac/webapp/templates/includes/clockss.html
- opac/webapp/templates/includes/footer.html
- requirements.txt
Atualiza a versão do opac_schema inclui no rodapé a licença e adiciona a permissão de preservação da clockss
Por commit 
Sugiro rodando a aplicação e verificando no HTML as alterações
Essa atividade é a mesma demanda para o opac, veja: https://github.com/scieloorg/opac/pull/3131
Nesse caso foi necessário que a inclusão da licença fosse responsiva.
[[Indique uma issue ao qual o pull request faz relacionamento.](https://github.com/scieloorg/opac/pull/3131)](https://github.com/scieloorg/opac/issues/3127)
https://github.com/scieloorg/opac/issues/3060
N/A
> Atualiza a versão do opac_schema inclui no rodapé a licença e adiciona a permissão de preservação da clockss

- opac/webapp/admin/views.py
- opac/webapp/main/views.py
Para a página informativa do journal, cria possibilidade de manter a página do legado, na ausência de conteúdo do Core 
Pelos commits
Acessar página informativa de algum periódico
N/A
#144 
https://github.com/scieloorg/opac_schema/pull/110
N/A
> Para a página informativa do journal, cria possibilidade de manter a página do legado, na ausência de conteúdo do Core 

- opac/webapp/factory.py
- requirements.txt
Ajusta a API para receber e armazenar collab
pelos commits
N/A
N/A
N/A
#214 
N/A
> Ajusta a API para receber e armazenar collab

- opac/webapp/templates/journal/includes/journal_info.html
Ajusta os links para as âncoras das páginas informativas dos periódicos
pelos commits
1. **Iniciar os Serviços**
Inicie os serviços dos projetos opac_5 e core.
2. **Selecionar um Periódico**
Escolha um periódico no OPAC para alterar as páginas informativas.
3. **Configurar a Função fetch_and_extract_section no OPAC**
No projeto opac, ajuste a função ```opac.webapp.utils.fetch_and_extract_section``` para apontar para o container local 
do serviço Django do projeto core.
Observação: Na minha configuração, foi necessário utilizar o gateway da rede Docker para conectar os containers.
Exemplo:
```python
def fetch_and_extract_section(collection_acronym, journal_acronym, language):
"""
Busca e extrai seção "journalContent" localizada no core.scielo.org
"""
class_name = "journalContent"
lang = …
```
> Ajusta os links para as âncoras das páginas informativas dos periódicos

- opac/webapp/templates/article/includes/floating_menu.html
Adiciona o novo menu flutuante na página do artigo.
Por commit
Acessando a página do artigo e verificando o comportamento pelo link: https://ramoncordini.com.br/scielo/novo-menu-flutuante/artigo/artigo-atual.html 
Idealmente essa implementação deveria de ser realizada no packtools e está porém não funciona por uma questão de precedência do javascript.
Esse PR complementa o PR: https://github.com/scieloorg/opac_5/pull/241
N/A
> Adiciona o novo menu flutuante na página do artigo.

- opac/webapp/translations/en/LC_MESSAGES/messages.po
Corrige no idioma Ingles (en) alguns termos que estavam sem tradução na interface do artigo. Veja os prints
Execute o sistema com as alterações e vá até a tela do artigo e compare com os prints aqui anexados.
Siga os passos descritos acima.
No video que relatou o erro (https://scielo.slack.com/files/U37RV0FD3/F08CWE223A9/screenshare_-_2025-02-12_11_48_36_am.webm) apareciam versões de artigos com idiomas frances. Não foi possível testar este idioma localmente. As correções se restringem ao idioma Ingles.
-
-
> Fix: Correção tradução do Menu idiomas na página do artigo. 

- requirements.txt
Atualiza packtools 4.11.10 - Melhorias de acessibilidade e de apresentação no modal de autoria
por commits
Acessar a página de um artigo
Clicar em "AUTORIA"
Observar a diferença
N/A
ANTES
DEPOIS
https://github.com/scieloorg/packtools/pull/978
n/a
> Atualiza packtools 4.11.10 - Melhorias de acessibilidade e de apresentação no modal de autoria

- opac/webapp/controllers.py
- opac/webapp/factory.py
Este pull request corrige problemas críticos de validação e tratamento de dados que estavam causando erros de execução na aplicação. Especificamente:
- **Corrige erro de AttributeError** quando `journal.last_issue` é `None` no método `set_last_issue_and_issue_count`
- **Previne TypeError** na função `get_issues_by_jid` quando não há artigos públicos disponíveis
- **Resolve erro de len() em NoneType** no `JournalFactory` quando `data.get('items')` retorna `None`
- **Melhora a robustez** das consultas ao banco de dados com parâmetros condicionais
A revisão deve começar pelos seguintes arquivos na ordem sugerida:
1. **`opac/webapp/controllers.py`** - Linhas 677-686 e 835-841
- Verificar a lógica condicional na função `get_issues_by_jid`
- Analisar a verificação de `journal.last_issue` antes …
> Correções de validação e tratamento de dados de journal e issue nos controllers e factory de journal

- .envs/.production-template/.flask
- opac/webapp/config/default.py
- opac/webapp/templates/base.html
Adiciona integração com o serviço DarkVisitors Analytics, permitindo monitoramento de tráfego de bots e agentes automatizados. A funcionalidade pode ser habilitada/desabilitada via variáveis de ambiente.
Começar pela configuração em `opac/webapp/config/default.py` (linhas 689-691) onde são definidas as variáveis de configuração com conversão booleana.
1. Definir as variáveis de ambiente:
```bash
export OPAC_ANALYTICS_AGENT_DARKVISITORS_ENABLED=true
export OPAC_ANALYTICS_AGENT_DARKVISITORS_PROJECT_KEY=sua-chave-aqui
```
2. Iniciar a aplicação Flask
3. Acessar qualquer página e inspecionar o HTML
4. Verificar se o script `https://darkvisitors.com/tracker.js` está presente no `<head>`
5. Testar com `ENABLED=false` para confirmar que o script não é incluído
O DarkVisitors é um serviço que …
> Adiciona suporte para DarkVisitors Analytics
