scieloorg/opac_5

- requirements.txt
Atualiza a versão de packtools para 3.2.5
https://github.com/scieloorg/packtools/releases/tag/3.2.5
> Atualiza a versão de packtools para 3.2.5

- requirements.txt
Atualiza a versão do packtools.
> Atualiza a versão do packtools.

- docker-compose.yml
Inclui dependência de opac_webapp no container de nginx.
pelo commits
```shell
docker-compose -f docker-compose.yml up -d
```
N/A
N/A
https://github.com/scieloorg/opac_5/issues/94
N/A
> Inclui depends_on no container nginx

- requirements.txt
Atualiza packtools v3.3.2 - correção e melhorias na página do artigos
- Corrige ausência de apresentação do rótulo dentro da seção "Edited by" by @robertatakenaka in https://github.com/scieloorg/packtools/pull/544
- Aplica design system recomendado no PR https://github.com/scieloorg/packtools/pull/531 by @robertatakenaka in https://github.com/scieloorg/packtools/pull/546
por commits
- https://github.com/scieloorg/packtools/pull/531
- https://github.com/scieloorg/opac/issues/2892
n/a
n/a
- https://github.com/scieloorg/packtools/pull/531
- https://github.com/scieloorg/opac/issues/2892
n/a
> Atualiza packtools v3.3.2 - correção e melhorias na página do artigos

- Dockerfile-dev
- opac/webapp/main/views.py
- requirements.txt
Atualiza Função fetch_data por um mais robusto que realiza tentativas de requisição
https://github.com/scieloorg/opac_5/commit/ec4a970fd33d37e5715c0878a5718ee8959aa781
N/A
N/A
https://github.com/scieloorg/opac_5/issues/102
N/A
> Atualiza Função fetch_data por um mais robusto que realiza tentativas de requisição

- opac/webapp/controllers.py
- opac/webapp/main/errors.py
- opac/webapp/main/views.py
Substitui os links na barra de navegação proveniente de core.scielo.org.
pelo commit  https://github.com/scieloorg/opac_5/commit/bc17c5b0af68de3ddadb8265f304c3d2420e901a
N/A
Em minha maquina, foi preciso alterar o arquivo /etc/docker/daemon.json e inserir:
```json
{
"dns": ["seu_dns_preferido", "8.8.8.8"]
}
```
N/A
#109 
N/A
> Substitui os links na barra de navegação proveniente de core.scielo.org.

- opac/webapp/main/views.py
Adiciona condição em 'replace_link' para verificar se o link está no formato esperado
pelo commit
1. Criar um EditorialBoard e associar a um periódico no core.scielo.
2. Ir no periódico em https://qa1.scielo.br/journal/journal_acron/about/#item-1
#113 
N/A
> Adiciona condição em 'replace_link' para verificar se o link está no formato esperado

- opac/webapp/translations/en/LC_MESSAGES/messages.po
- opac/webapp/translations/messages.pot
Corrige os termos ativos e terminado e mensagem de erro
> Corrige os termos ativos e terminado e mensagem de erro

- requirements.txt
Atualiza a versão de packtools para v4.5.0 (correção de menu esquerdo da página do artigo layout v3.0)
por commits
Ver #134
n/a
n/a
#134
n/a
> Atualiza a versão de packtools para v4.5.0 (correção de menu esquerdo da página do artigo layout v3.0)

- docker-compose-dev.yml
- docker-compose.yml
Esta Pull Request adiciona a configuração necessária para incluir o serviço MinIO no arquivo docker-compose.yml.
pelo commit
1. make up
N/A
N/A
N/A
N/A
> Adiciona Serviço MinIO ao Docker Compose

- Makefile
Adiciona comando update ao Makefile para remoção e atualização de containers de produção
pelos commits
1. make update COMPOSE_DEV=docker-compose.yml
N/A
N/A
N/A
N/A
> Adiciona comando update ao Makefile para remoção e atualização de containers de produção

- Makefile
Atualiza a variável COMPOSE_DEV para compose no Makefile para manter o padrão em outros códigos da scieloorg.
pelo commit
1. make update compose=docker-compose.yml
N/A
N/A
N/A
N/A
> Atualizar variável COMPOSE_DEV para compose no Makefile

- opac/webapp/admin/views.py
Habilita Criação, Edição e Remoção de Notícias na área administrativa
pelos commits
Na área administrativa, criar, editar ou excluir alguma notícia
N/A
N/A
#156 
N/A
> Habilita Criação, Edição e Remoção de Notícias na área administrativa

- opac/webapp/translations/es_ES/LC_MESSAGES/messages.po
Corrige tradução de Número Seguinte em espanhol
pelos commits
acessar página sobre o periodico.
N/A
#167 
N/A
> Corrige tradução de Número Seguinte em espanhol

- opac/webapp/translations/pt_PT/LC_MESSAGES/messages.po
Cria arquivos de tradução para pt_PT
pelo commit
N/A
N/A
N/A
#161 
N/A
> Cria arquivos de tradução para pt_PT

- opac/webapp/admin/views.py
Habilita criação e remoção de coleções na área administrativa
pelos commits
Acessar área administrativar e criar coleção e deletar
N/A
#176 
N/A
> Habilita criação e remoção de coleções na área administrativa

- .envs/.production/.flask
- .envs/.production/.metrics
- .envs/.production/.minio
- .envs/.production/.monitoring-apm
- .envs/.production/.redis
- .envs/.production/.server
- docker-compose.yml
Adição de arquivos de configuração de ambiente e modificação no arquivo docker-compose.yml para utiliza-los.
pelos commits
```
make up compose=docker-compose.yml
```
N/A
N/A
#178 
N/A
> Adiciona arquivos de ambiente e modifica docker-compose para utilizá-los

- .envs/.production-template/.flask
- opac/webapp/config/default.py
- opac/webapp/main/views.py
- opac/webapp/templates/includes/language.html
- opac/webapp/utils/utils.py
Adiciona a variável de ambiente OPAC_LANGUAGES e garante que seja apresentado novo idioma na interface.
Sugiro que seja feito por commit e rodando os teste unitários.
Rodando a aplicação e realizando alterações nas variáveis de ambiente para idiomas e troca de idioma na interface.
Além de adicionar a capacidade de adicionar novos idiomas, foi realizado uma organização de códigos recentemente adicionados em módulo não recomendados.
Sugiro que também seja testado das páginas secundárias dos periódicos.
https://github.com/scieloorg/opac_5/issues/174
N/A
> Adiciona a variável de ambiente OPAC_LANGUAGES e garante que seja apresentado novo idioma na interface.

- opac/webapp/factory.py
Corrige atribuição de valores para is_public de Journal, Issue e Article e journal.current_status.
Corrige JournalFactory e ArticleFactory para atribuir valor para is_public para journal, issue e article, e current_status para journal.
O valor de current_status era computado ao receber os dados, no entanto, estava incorreto quando o periódico ainda está sendo trabalhado, é um periódico recém ingressado na coleção.
A atribuição de is_public foi alterada ao considerar que, às vezes, o objetivo é despublicar o journal, issue, ou artigo.
por commits
Executando `/api/v1/journal` e `/api/vi1/article`
n/a
n/a
n/a
n/a
> Corrige atribuição de valores para is_public de Journal, Issue e Article e journal.current_status

- docker-compose.yml
Fix: Name file env
pelo commit
realizando build do projeto
N/A
N/A
#198 
N/A
> Fix: Name file env

- opac/webapp/admin/views.py
Adiciona o campo "old_information_page" ao formulário de edição do periódico
pelos commits
Editar algum periódico na parte de edição na área administrativa
N/A
N/A
#207 
N/A
> Adiciona o campo "old_information_page" ao formulário de edição do periódico

- opac/webapp/factory.py
Recebe e atribui valores para doi_with_lang e relatad_articles em ArticleFactory
pelos commits
N/A
N/A
N/A
#215 
#212 
N/A
> Recebe e atribui valores para doi_with_lang e relatad_articles em ArticleFactory

- opac/webapp/templates/issue/toc.html
Adapta exibição da seção do artigo para o idioma da sessão no toc.html
Acessar: http://0.0.0.0:8000/j/abb/i/2022.v36/
https://github.com/scieloorg/opac_schema/blob/2bb30ecb425eaa282be0492f9eaacd64fd6b3909/opac_schema/v1/models.py#L851
N/A
#235 
N/A
> Adapta exibição da seção do artigo para o idioma da sessão no toc.html

- opac/webapp/main/views.py
Corrige erro ao tentar acessar um atributo em um objeto NoneType ao visualizar a página de um periódico sem nenhuma página cadastrada no sistema.
pelos commits
Acessar "sobre o periódico" sem ter nenhuma página cadastrada.
N/A
#244 
N/A
> Fix: Error NoneType object has no attribute 'content' about_journal

- opac/webapp/controllers.py
em get_journals, inclui parametro "inprogress" para buscar journals em  andamento
pelos commits
N/A
N/A
#251 
N/A
> Inclui status "inprogress" para identificar os journals em andamento

- opac/webapp/factory.py
Corrige a ausência do campo abstract_languages e garante que items sejam listas vazias no lugar de None
> Corrige a ausência do campo abstract_languages e garante que items sejam listas vazias no lugar de None

- opac/webapp/templates/journal/includes/journal_info.html
- inserir selo do creative commons nas páginas do periódico, 
- alterar ordem do item de menu "política editorial", 
- ajustar posicionamento do issn impresso e online
atualize e rode o sistema e verifique nas telas do periódico se os itens citados estão de acordo com o print abaixo.
Siga os passos descritos acima.
-
#236 
-
> Fix: Ajustes journal_info.html

- requirements.txt
…vras-chave, seção disponibilidade de dados
#267  
#266 
#265 
#258 
> Atualiza a versão packtools 4.11.4 - página do artigo - resumos, palavras-chave, seção disponibilidade de dados

- opac/webapp/config/default.py
> Corrige o valor padrão de OPAC_SITE_LICENSE_URL e a forma de estabelecer os valores das variáveis relacionadas com a licença

- .envs/.production-template/.db-sqlite
> Corrige valor padrão de .envs/.production-template/.db-sqlite

- .envs/.production-template/.db-sqlite
- Makefile
- docker-compose.yml
- opac/app.py
Este PR corrige o arquivo de definição de variáveis de ambiente com o objetivo de resolver um erro de acesso ao arquivo `opac.sqlite`.
Esse erro está ocorrendo na República Dominicana.
---
Sugiro que seja feita uma nova instalação da aplicação utilizando os comandos documentados no seguinte link:
🔗 https://github.com/scieloorg/opac_5/wiki/Website-(opac)-installation
Essa documentação foi atualizada com os seguintes novos comandos auxiliares:
- `make fix_perms compose=docker-compose.yml`  
- `make check_perms compose=docker-compose.yml`  
- `flask --app opac.app create_empty_sqlite`  
- `make backup compose=docker-compose.yml`  
Também foi adicionado um novo comando para realizar o backup do banco de dados SQLite (`opac.sqlite`).
---
Para testar, utilize o guia de instalação disponível em: …
> Corrige acesso a base de dados opac.sqlite e adiciona novos recursos de verificação de permissão.

- opac/webapp/factory.py
- opac/webapp/main/views.py
Corrige a ausência do campo abstract_languages e garante que items sejam listas vazias no lugar de None
por commits
Acessando página do sumário e verificando se os resumos são apresentados
> Fix a atribuição de `article.abstract_languages`

- opac/webapp/templates/issue/toc.html
- Adicionado bloco with para melhor controle de variáveis
- Implementação de renderização condicional para seções
- Aplicado filtro safe para evitar problemas de escape HTML
- Remoção de debug code comentado
Resolves: Problemas de renderização de seções em artigos
Quando aplicável e se fizer possível adicione screenshots que …
> Fix: Melhoria no template toc.html para renderização de seções

- opac/webapp/controllers.py
> Fix controller quando journal nao tem issues 2

- opac/webapp/controllers.py
- opac/webapp/factory.py
- opac/webapp/templates/issue/toc.html
> Faz correções no template do sumário (seções), total de issues do journal, bug de condicional

- opac/webapp/controllers.py
- opac/webapp/main/views.py
- opac/webapp/templates/article/includes/levelMenu.html
- opac/webapp/templates/issue/includes/alternative_header.html
- opac/webapp/templates/journal/includes/alternative_header.html
- opac/webapp/templates/journal/includes/levelMenu.html
> Aprimora e corrige navegação em issues e articles

- requirements.txt
…acao_de_numero_sobrescrito_relacionado_com_referencias_numeradas
#308 
> Atualiza packtools 4.11.12 para corrigir na_pagina_do_artigo_apresentacao_de_numero_sobrescrito_relacionado_com_referencias_numeradas

- opac/webapp/templates/article/includes/meta.html
> Corrige o valor de meta name citation_publication_date
